name: Tests

on:
  push: ~
  pull_request: ~

jobs:
  build:
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']

    runs-on: ubuntu-latest

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Download dependencies
        uses: ramsey/composer-install@v2

      - name: Run test suite on PHP ${{ matrix.php }}
        run: composer run-script test

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: ./build/logs/clover.xml
          verbose: true
